server:
  port: 8080

spring:
  application:
    name: user-service
  profiles:
    include: common,kafka
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: youzheng_web
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 500
  datasource:
    url: jdbc:mysql://localhost:3306/template
    username: root
    password: dnwjd123
    hikari:
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
    datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL

---